# Generated by Django 4.2.30 on 2026-04-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_name', models.CharField(blank=True, default='', max_length=120)),
                ('father_name', models.CharField(blank=True, default='', max_length=120)),
                ('parents_phone', models.CharField(blank=True, default='', max_length=30)),
                ('parents_occupation', models.CharField(blank=True, default='', max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_certificates/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.student')),
            ],
            options={
                'ordering': ['-year', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_result', models.CharField(blank=True, default='', max_length=50)),
                ('semester', models.CharField(blank=True, default='', max_length=50)),
                ('unit_test_marks', models.JSONField(blank=True, default=dict, null=True)),
                ('surprise_test_marks', models.JSONField(blank=True, default=dict, null=True)),
                ('performance', models.TextField(blank=True, default='')),
                ('creativity', models.TextField(blank=True, default='')),
                ('teacher_remarks', models.TextField(blank=True, default='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='api.student')),
            ],
        ),
    ]
