# Generated by Django 4.2.30 on 2026-04-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_enhanced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='academicdetails',
            name='surprise_test_marks',
        ),
        migrations.RemoveField(
            model_name='academicdetails',
            name='unit_test_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
