# Generated by Django 4.2.30 on 2026-04-18 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('api', 'UserProfile')
    for u in User.objects.all():
        UserProfile.objects.get_or_create(
            user=u,
            defaults={
                'role': 'principal',
                'assigned_class': '',
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_sync_total_marks_from_exam_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_remove_attendance_from_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher')], default='class_teacher', max_length=32)),
                ('assigned_class', models.CharField(blank=True, default='', help_text='Exact student_class label for class teachers (e.g. 6, 10A).', max_length=40)),
                ('assigned_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teachers', to='marks.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('marks_create', 'Marks create'), ('marks_update', 'Marks update'), ('marks_delete', 'Marks delete'), ('attendance_create', 'Attendance create'), ('attendance_update', 'Attendance update'), ('teacher_create', 'Teacher create')], max_length=32)),
                ('target', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(seed_profiles_for_existing_users, noop),
    ]
