# Generated by Django 4.2.30 on 2026-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_email_otp'),
    ]

    operations = [
        migrations.RenameModel(old_name='EmailOTP', new_name='LoginOTP'),
        migrations.RenameField(
            model_name='loginotp',
            old_name='otp_hash',
            new_name='otp',
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='otp',
            field=models.CharField(
                help_text='SHA-256 hex of the 6-digit code (peppered).',
                max_length=64,
            ),
        ),
    ]
