# Generated by Django 4.2.30 on 2026-04-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_login_otp_rename'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginotp',
            new_name='api_loginot_email_d0f5fa_idx',
            old_name='api_emailot_email_53cfb1_idx',
        ),
    ]
