# Generated by Django 4.2.30 on 2026-04-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_api_emailot_email_53cfb1_idx_api_loginot_email_d0f5fa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Self-registered users start pending until Principal/Vice Principal approves.', max_length=16),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('marks_create', 'Marks create'), ('marks_update', 'Marks update'), ('marks_delete', 'Marks delete'), ('attendance_create', 'Attendance create'), ('attendance_update', 'Attendance update'), ('teacher_create', 'Teacher create'), ('user_create', 'User create'), ('user_approve', 'User approve'), ('user_reject', 'User reject'), ('user_role_update', 'User role update')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('class_teacher', 'Class Teacher'), ('subject_teacher', 'Subject Teacher'), ('staff', 'Staff (Admin)'), ('unassigned', 'Unassigned')], default='unassigned', max_length=32),
        ),
    ]
