# Generated by Django 4.2.30 on 2026-04-20 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marks', '0004_sync_total_marks_from_exam_type'),
        ('api', '0015_alter_userprofile_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('class_name', models.CharField(db_index=True, max_length=40)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_original', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions', to='marks.subject')),
                ('substitute_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions_as_substitute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time', 'class_name', 'id'],
                'indexes': [models.Index(fields=['date', 'status'], name='api_substit_date_b0501f_idx'), models.Index(fields=['date', 'start_time'], name='api_substit_date_950e28_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=40)),
                ('day', models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat')], db_index=True, max_length=3)),
                ('start_time', models.TimeField(db_index=True)),
                ('end_time', models.TimeField(db_index=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_slots', to='marks.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedule_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'start_time', 'end_time', 'class_name', 'id'],
                'indexes': [models.Index(fields=['teacher', 'day', 'start_time'], name='api_classsc_teacher_9b6bc4_idx'), models.Index(fields=['day', 'start_time', 'end_time'], name='api_classsc_day_5ad304_idx')],
            },
        ),
    ]
