# Generated by Django 4.2.30 on 2026-04-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_substitution_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.JSONField(blank=True, default=list, help_text='Advanced: multiple class labels assigned to this teacher (e.g. ["5", "6"]).'),
        ),
    ]
