# Generated by Django 4.2.30 on 2026-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_sync_total_marks_from_exam_type'),
        ('api', '0017_userprofile_assigned_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, help_text='Advanced: allow one subject teacher to handle multiple subjects.', related_name='subject_teachers_many', to='marks.subject'),
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='assigned_classes',
            new_name='assigned_classes_json',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this staff user can access (for class/subject teachers).', related_name='teachers', to='api.schoolclass'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _forward_migrate_assigned_classes(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_classes_json',
        ),
    ]


def _forward_migrate_assigned_classes(apps, schema_editor):
    UserProfile = apps.get_model('api', 'UserProfile')
    SchoolClass = apps.get_model('api', 'SchoolClass')

    # marks.Subject exists due to dependency
    Subject = apps.get_model('marks', 'Subject')

    for prof in UserProfile.objects.all().iterator():
        raw = getattr(prof, 'assigned_classes_json', None) or []
        classes = [str(c).strip() for c in raw if str(c).strip()]
        single = (getattr(prof, 'assigned_class', '') or '').strip()
        if not classes and single:
            classes = [single]

        if classes:
            cls_objs = []
            for name in classes:
                obj, _ = SchoolClass.objects.get_or_create(name=name)
                cls_objs.append(obj)
            prof.assigned_classes.set(cls_objs)

        # If a legacy single subject was set, also seed the new M2M.
        sid = getattr(prof, 'assigned_subject_id', None)
        if sid:
            try:
                subj = Subject.objects.get(pk=sid)
                prof.assigned_subjects.add(subj)
            except Exception:
                pass
