# Generated by Django 4.2.30 on 2026-04-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_sms_advanced_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReportSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_report_sends', to='api.student')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
