"""Report card PDF (ReportLab)."""

from __future__ import annotations

import io
from typing import Any

from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from marks.services.results_aggregate import student_result_detail


def build_reportcard_pdf(student_id: int, exam_slug: str) -> bytes | None:
    detail = student_result_detail(student_id, exam_slug)
    if not detail:
        return None
    st = detail['student']
    agg = {
        'subjects': detail['subjects'],
        'total_marks_obtained': detail['total_marks_obtained'],
        'total_marks_max': detail['total_marks_max'],
        'percentage': detail['percentage'],
        'grade': detail['grade'],
        'teacher_remarks': detail.get('teacher_remarks') or '',
    }

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.2 * cm,
        bottomMargin=1.2 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name='Title',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=6,
        textColor=colors.HexColor('#0f172a'),
    )
    sub_style = ParagraphStyle(
        name='Sub',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#64748b'),
    )
    school = getattr(settings, 'SCHOOL_NAME', 'Student Management School')

    story = []
    story.append(Paragraph(school, title_style))
    story.append(Paragraph('Report card', sub_style))
    story.append(Spacer(1, 0.4 * cm))

    meta = [
        ['Student', st['name']],
        ['Class', str(st['student_class'])],
        ['Roll no.', str(st['roll_no'])],
        ['Exam', detail['exam_type_label']],
        ['Rank in class', f"{detail['rank']} / {detail['total_in_class']}"],
    ]
    t_meta = Table(meta, colWidths=[4 * cm, 10 * cm])
    t_meta.setStyle(
        TableStyle(
            [
                ('FONT', (0, 0), (-1, -1), 'Helvetica', 9),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#64748b')),
                ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#0f172a')),
                ('LINEBELOW', (0, -1), (-1, -1), 0.25, colors.HexColor('#e2e8f0')),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]
        )
    )
    story.append(t_meta)
    story.append(Spacer(1, 0.5 * cm))

    subj_rows = [['Subject', 'Obtained', 'Max', '%', 'Grade']]
    for s in agg['subjects']:
        subj_rows.append(
            [
                s['subject'],
                str(s['marks_obtained']),
                str(int(s['total_marks']) if s['total_marks'] == int(s['total_marks']) else s['total_marks']),
                f"{s['percentage']:.1f}",
                s['grade'],
            ]
        )
    subj_rows.append(
        [
            'TOTAL',
            str(agg['total_marks_obtained']),
            str(agg['total_marks_max']),
            f"{agg['percentage']:.2f}",
            agg['grade'],
        ]
    )
    t_sub = Table(subj_rows, colWidths=[6 * cm, 2.2 * cm, 2 * cm, 2 * cm, 2 * cm])
    t_sub.setStyle(
        TableStyle(
            [
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
                ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 8),
                ('FONT', (0, 1), (-1, -1), 'Helvetica', 8),
                ('GRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#e2e8f0')),
                ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#f8fafc')),
                ('FONT', (0, -1), (-1, -1), 'Helvetica-Bold', 9),
            ]
        )
    )
    story.append(t_sub)
    story.append(Spacer(1, 0.4 * cm))

    remarks = (agg.get('teacher_remarks') or '').strip()
    if remarks:
        story.append(Paragraph('<b>Teacher remarks</b>', styles['Normal']))
        story.append(Paragraph(remarks.replace('\n', '<br/>'), styles['Normal']))
    else:
        story.append(Paragraph('<i>No remarks on file.</i>', sub_style))

    story.append(Spacer(1, 0.8 * cm))
    story.append(Paragraph('Generated by SMS · For queries contact the school office.', sub_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
