# Generated by Django 4.2.30 on 2026-04-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_sms_advanced_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('MID_SEM', 'Mid Sem'), ('SEMESTER', 'Semester')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('exam_date', models.DateField()),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_rows', to='marks.examtype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_marks', to='api.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_rows', to='marks.subject')),
            ],
            options={
                'ordering': ['-exam_date', '-id'],
                'indexes': [models.Index(fields=['student', 'exam_type'], name='marks_marks_student_3c2ecb_idx'), models.Index(fields=['student', 'subject'], name='marks_marks_student_e4bf4d_idx')],
            },
        ),
    ]
